[workspace]
members = [
        "breakpad-symbols",
        "minidump",
        "minidump-common",
        "minidump-processor",
        "minidump-stackwalk",
        "minidump-symbol-client",
        "minidump-synth",
]
exclude = [
    "testdata/*",
]
